package com.example.zajecia7doktorki.model;

public enum ActionPerformed {

    REMOVING_CUSTOMER, LOCKING_CUSTOMER, DISABLING_CUSTOMER, UNLOCKING_CUSTOMER, ENABLING_CUSTOMER, EDITING_APPOINTMENT, DELETING_APPOINTMENT
}
